language: rust

install:
  - wget https://github.com/jedisct1/libsodium/releases/download/1.0.10/libsodium-1.0.10.tar.gz
  - tar xvfz libsodium-1.0.10.tar.gz
  - cd libsodium-1.0.10 && ./configure --prefix=/usr && make && sudo make install && cd ..

branches:
  only:
    - master

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

notifications:
  irc: 'irc.freenode.org#cryptosphere'
